development: &defaults
  achievement_cache_time: 3600    # Seconds to cache achievement data on a per user/game basis
  user_cache_time: 86400
  friends_cache_time: 86400
  games:
    - shortname: tf2 
      fullname: Team Fortress 2
      gameid: 440
    - shortname: l4d
      fullname: Left 4 Dead
      gameid: 550
    - shortname: portal2
      fullname: Portal 2
      gameid: 620
    - shortname: portal
      fullname: Portal
      gameid: 400
    - shortname: alienswarm
      fullname: Alien Swarm
      gameid: 630

production:
  achievement_cache_time: 600
  <<: *defaults
